#!/bin/sh
# OpenSC Project Windows Build
# Copyright (c) 2008 The OpenSC Project
# Copyright (C) 2008 Alon Bar-Lev <alon.barlev@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# msys:
# No environment required, unless buggy wget which needs
# full version:
# WGET=/c/msys/1.0/bin/wget
#
# cross compile:
# CHOST=i686-pc-mingw32 CBUILD=i686-pc-linux-gnu
#

die() {
	local m="$1"

	echo "FATAL: ${m}" >&2
	exit 1
}

get_my_dir() {
	local o="$(pwd)"
	cd "$(dirname "$0")"
	pwd
	cd "${o}"
}

fixup_la() {
	local f

	echo "Fixup libtool files"
	for f in "${IMAGEROOT}/lib"/*.la; do
		sed 's#//#'"${IMAGEROOT}"'/#g' "${f}" > "${f}.tmp"
		mv "${f}.tmp" "${f}"
	done
}

restore_la() {
	local f

	echo "Restore libtool files"
	for f in "${IMAGEROOT}/lib"/*.la; do
		sed 's#'"${IMAGEROOT}"'/#//#g' "${f}" > "${f}.tmp"
		mv "${f}.tmp" "${f}"
	done
}

download1() {
	local url="$1"
	local prefix="$(basename "${url}" | sed 's/-.*//g')"

	if ! [ -n "$(ls "${DISTDIR}/${prefix}"* 2> /dev/null)" ]; then
		"${WGET}" ${WGET_OPTS} --directory-prefix="${DISTDIR}" \
			"${url}" \
			|| die "Cannot download ${url}"
	fi
}

download() {
	if ! [ -e "${DISTDIR}" ]; then
		mkdir -p "${DISTDIR}" || die "Cannot create '${DISTDIR}'"
	fi
	download1 "http://www.zlib.net/zlib-${ZLIB_VERSION}.tar.gz"
	download1 "http://ftp.gnu.org/gnu/libtool/libtool-${LIBTOOL_VERSION}.tar.gz"
	download1 "http://mirrors.usc.edu/pub/openssl/snapshot/openssl-${OPENSSL_VERSION}.tar.gz"
	download1 "http://www.opensc-project.org/files/opensc/opensc-${OPENSC_VERSION}.tar.gz"
	download1 "http://www.opensc-project.org/files/libp11/libp11-${LIP11_VERSION}.tar.gz"
	download1 "http://www.opensc-project.org/files/engine_pkcs11/engine_pkcs11-${ENGINE_PKCS11_VERSION}.tar.gz"
#	download1 "http://www.opensc-project.org/files/scb/csp11-${CSP11_VERSION}.tar.gz"
#	download1 "http://www.opensc-project.org/svn/scb/trunk/putty-${PUTTY_VERSION}.tar.gz"

	if [ "$(ls "${DISTDIR}" | wc -l | sed 's/[ \t]//g')" != 6 ]; then
		die "distfiles is unclean."
	fi
}

create_layout() {
	[ -e "${IMAGEROOT}" ] && rm -fr "${IMAGEROOT}"
	[ -e "${BUILDROOT}" ] && rm -fr "${BUILDROOT}"

	mkdir -p "${IMAGEROOT}" || die "Cannot create '${IMAGEROOT}'"
	mkdir -p "${BUILDROOT}" || die "Cannot create '${BUILDROOT}'"
}

extract() {
	local f

	for f in "${DISTDIR}"/*; do
		local extra=""
		echo "Extract '$f'"
		echo "$f" | grep -q '\.bz2' && extra="${extra}j"
		echo "$f" | grep -q '\.gz' && extra="${extra}z"
		tar -C "${BUILDROOT}" -x${extra}f "${f}" || die "Extract '${f}'"
	done

	for f in "${PATCHDIR}"/*; do
		product="$(echo "${f}" | sed -e 's#.*/##g' -e 's/-.*//g')"
		if [ -d "${BUILDROOT}/${product}"* ]; then
			echo "Patch: '$f'"
			patch -d "${BUILDROOT}/${product}"* -p1 < "${f}" || die "Patch '${f}'"
		fi
	done
}

build_dep() {
	echo "Build zlib"
	cd "${BUILDROOT}/zlib"* || die "cd zlib"
	make -f win32/Makefile.gcc \
		PREFIX=${CHOST:+${CHOST}-} \
		INCLUDE_PATH="${IMAGEROOT}/include" \
		LIBRARY_PATH="${IMAGEROOT}/lib" \
		BINARY_PATH="${IMAGEROOT}/bin" \
		install || \
		die "make zlib"

	echo "Build libtool"
	cd "${BUILDROOT}/libtool"* || die "cd libtool"
	./configure ${CONFIGOPTS} || die "Configure libtool"
	make ${MAKEOPTS} install DESTDIR="${IMAGEROOT}" || die "make opensc"
	fixup_la

	echo "Build openssl"
	cd "${BUILDROOT}/openssl"* || die "cd openssl"
	# cms cannot compile in latest (20080314) snapshot
	./Configure --prefix="//" --cross-compile-prefix=${CHOST:+${CHOST}-} \
		no-zlib shared mingw \
		|| die "Configure openssl"
	perl util/mkdef.pl crypto update
	make depend install INSTALL_PREFIX="${IMAGEROOT}" INSTALLTOP="/" MANDIR="/tmp" \
		|| die "make openssl"
	rm -fr "${IMAGEROOT}/tmp"

	cd "${SCRIPTROOT}"
	restore_la
}

build_opensc() {
	fixup_la

	echo "Build opensc"
	cd "${BUILDROOT}/opensc"* || die "cd opensc"
	./configure ${CONFIGOPTS} \
		--enable-openssl --enable-zlib --enable-pcsc --enable-doc \
		LTLIB_CFLAGS="-I${IMAGEROOT}/include" LTLIB_LIBS="-L${IMAGEROOT}/lib -lltdl" \
		ZLIB_CFLAGS="-I${IMAGEROOT}/include" ZLIB_LIBS="-L${IMAGEROOT}/lib -lzdll" \
		OPENSSL_CFLAGS="-I${IMAGEROOT}/include" OPENSSL_LIBS="-L${IMAGEROOT}/bin -leay32" \
		|| die "Configure opensc"
	make ${MAKEOPTS} install DESTDIR="${IMAGEROOT}" || die "make opensc"
	fixup_la

	echo "Build libp11"
	cd "${BUILDROOT}/libp11"* || die "cd libp11"
	./configure ${CONFIGOPTS} \
		--enable-doc \
		LTLIB_CFLAGS="-I${IMAGEROOT}/include" LTLIB_LIBS="-L${IMAGEROOT}/lib -lltdl" \
		OPENSSL_CFLAGS="-I${IMAGEROOT}/include" OPENSSL_LIBS="-L${IMAGEROOT}/bin -leay32" \
		|| die "Configure libp11"
	make ${MAKEOPTS} install DESTDIR="${IMAGEROOT}" || die "make libp11"

	fixup_la

	echo "Build engine_pkcs11"
	cd "${BUILDROOT}/engine_pkcs11"* || die "cd engine_pkcs11"
	./configure ${CONFIGOPTS} \
		--enable-doc \
		--with-enginesdir="/lib/engines" \
		OPENSSL_CFLAGS="-I${IMAGEROOT}/include" OPENSSL_LIBS="-L${IMAGEROOT}/bin -leay32" \
		LIBP11_CFLAGS="-I${IMAGEROOT}/include" LIBP11_LIBS="-L${IMAGEROOT}/lib -lp11" \
		|| die "Configure engine_pkcs11"
	make ${MAKEOPTS} install DESTDIR="${IMAGEROOT}" || die "make engine_pkcs11"

	fixup_la

if false; then
	echo "Build csp11"
	cd "${BUILDROOT}/csp11"*
	./configure ${CONFIGOPTS} \
		|| die "Configure csp11"
	make ${MAKEOPTS} install DESTDIR="${IMAGEROOT}" || die "make csp11"

	echo "Build putty"
	cd "${BUILDROOT}/putty"*
	cd windows
	make -f Makefile.cyg TOOLPATH=${CHOST}-
	cp *.exe "${IMAGEROOT}/bin"
fi

	cd "${SCRIPTROOT}"
	restore_la
}

copy_docs() {
	mkdir -p "${IMAGEROOT}/share/doc/package"
	cp "${SCRIPTROOT}/README" "${SCRIPTROOT}/COPYING"* "${IMAGEROOT}/share/doc/package" || die "package docs"
	ls "${DISTDIR}" > "${IMAGEROOT}/share/doc/package/components.lst" || die "components.lst"
}

copy_sources() {
	mkdir -p "${IMAGEROOT}/src/patches"
	cp "${DISTDIR}"/* "${IMAGEROOT}/src" || die "sources"
	cp "${PATCHDIR}"/* "${IMAGEROOT}/src/patches" || die "patches"
}

clean_empty_dirs() {
	find "${IMAGEROOT}" -type d | sort -r | xargs rmdir 2> /dev/null
}

SCRIPTROOT="$(get_my_dir)"

WGET="${WGET:-wget}"
#WGET_OPTS
MAKEOPTS="${MAKEOPTS:--j2}"
#CHOST
CTARGET="${CTARGET:-${CHOST}}"
CBUILD="${CBUILD:-${CHOST}}"
IMAGEROOT="${IMAGEROOT:-${SCRIPTROOT}/image}"
BUILDROOT="${BUILDROOT:-${SCRIPTROOT}/tmp}"
DISTDIR="${DISTDIR:-${SCRIPTROOT}/distfiles}"
PATCHDIR="${SCRIPTROOT}/patches"

CONFIGOPTS="--prefix=/ --host=${CHOST} --target=${CTARGET} --build=${CBUILD} PKG_CONFIG=true"

. "${SCRIPTROOT}/fetch.versions" || die "Cannot source versions"

download
create_layout
extract
build_dep
build_opensc
copy_docs
copy_sources
clean_empty_dirs

exit 0
