#!/bin/sh
# OpenSC Project Cross Compile Build
# Copyright (c) 2008-2009 The OpenSC Project
# Copyright (C) 2008-2009 Alon Bar-Lev <alon.barlev@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# msys:
# No environment required, unless buggy wget which needs
# full path:
# WGET=/c/msys/1.0/bin/wget
#
# Cross compile for Windows:
# IMAGEROOT=`pwd`/image-win32 CHOST=i686-w64-mingw32 CBUILD=x86_64-pc-linux-gnu ./build
# IMAGEROOT=`pwd`/image-win64 CHOST=x86_64-w64-mingw32 CBUILD=x86_64-pc-linux-gnu ./build
# Cross compile for uClibc:
# CHOST=i586-pc-linux-uclibc CBUILD=i686-pc-linux-gnu ./build
#

die() {
	local m="$1"

	echo "FATAL: ${m}" >&2
	exit 1
}

get_full_path() {
	local d="$1"
	( cd "${d}" 2> /dev/null && pwd )
}

fixup_la() {
	local f

	echo "Fixup libtool files"
	find "${IMAGEROOT}" -name '*.la' | while read f; do
		local top="$(dirname "$(dirname "$(echo "${f}")")" | sed 's#//#/#g')"
		sed 's#//#'"${top}"'/#g' "${f}" > "${f}.tmp"
		mv "${f}.tmp" "${f}"
	done
}

restore_la() {
	local f

	echo "Restore libtool files"
	find "${IMAGEROOT}" -name '*.la' | while read f; do
		local x="$(echo "${IMAGEROOT}" | sed 's#/$##')"
		sed 's#'"${x}"'/[^/]*/lib#//lib#g' "${f}" > "${f}.tmp"
		mv "${f}.tmp" "${f}"
	done
}

geturl() {
	if [ -n "${WGET_MODE}" ]; then
		"${WGET}" ${WGET_OPTS} --directory-prefix="${SOURCESROOT}" "${url}"
	else
		(
			cd "${SOURCESROOT}" && \
				"${CURL}" ${CURL_OPTS} "${url}"
		)
	fi
}

download1() {
	local url="$1"
	local prefix="$(basename "${url}" | sed 's/-.*//g')"

	if ! [ -n "$(ls "${SOURCESROOT}/${prefix}"* 2> /dev/null)" ]; then
		geturl ${url} || die "Cannot download ${url}"
	fi
}

download() {
	if ! [ -e "${SOURCESROOT}" ]; then
		mkdir -p "${SOURCESROOT}" || die "Cannot create '${SOURCESROOT}'"
	fi

	for url in \
		${ZLIB_URL} ${LZO_URL} ${LIBTOOL_URL} ${ICONV_URL} \
		${OPENSSL_URL} ${OPENCT_URL} ${OPENSC_URL} ${LIBP11_URL} \
		${ENGINE_PKCS11_URL} ${PKCS11_HELPER_URL} ${OPENVPN_URL}; \
		do
		download1 "${url}"
	done

	if [ "$(ls "${SOURCESROOT}" | wc -l | sed 's/[ \t]//g')" != 11 ]; then
		die "sources is unclean."
	fi
}

create_layout() {
	[ -e "${IMAGEROOT}" ] && rm -fr "${IMAGEROOT}"
	[ -e "${BUILDROOT}" ] && rm -fr "${BUILDROOT}"

	mkdir -p "${IMAGEROOT}" || die "Cannot create '${IMAGEROOT}'"
	mkdir -p "${BUILDROOT}" || die "Cannot create '${BUILDROOT}'"
}

extract() {
	local f

	for f in "${SOURCESROOT}"/*; do
		local extract=""
		echo "Extract '$f'"
		case "${f}" in
			*.gz)
				extract="gunzip -c"
			;;
			*.bz2)
				extract="bunzip2 -c"
			;;
			*.lzma)
				extract="unlzma"
			;;
			*)
				extract="cat"
			;;
		esac
		${extract} < "${f}" | tar -C "${BUILDROOT}" -xf - || die "Extract '${f}'"
	done

	for f in "${PATCHDIR}"/*.patch "${PATCHDIR}"/*.sh; do
		product="$(echo "${f}" | sed -e 's#.*/##g' -e 's/-[0-9].*//g')"
		if [ -d "${BUILDROOT}/${product}"* ]; then
			if echo "${f}" | grep '.patch$' > /dev/null; then
				echo "Patch: '$f'"
				patch -d "${BUILDROOT}/${product}"* -p1 < "${f}" || die "Patch '${f}'"
			else
				echo "Running: '$f'"
				$( cd "${BUILDROOT}/${product}"*; "${f}" ) || die "Patch '${f}'"
			fi
		fi
	done
}

fixup_win64_libtool() {
	# Fix win64 libtool
	find "${BUILDROOT}" -name ltmain.sh | while read f; do
		sed 's/architecture: i386)?'\''/architecture: i386)?|file format pe-x86-64'\''/' < "${f}" > "${f}.tmp"
		mv "${f}.tmp" "${f}"
	done
}

build_dep() {
	echo "Build zlib"
	cd "${BUILDROOT}/zlib"* || die "cd zlib"
	if [ -n "${BUILD_FOR_WINDOWS}" ]; then
		${MAKE} -f win32/Makefile.gcc \
			PREFIX=${CHOST:+${CHOST}-} \
			INCLUDE_PATH="${OPENSC_ROOT}/include" \
			LIBRARY_PATH="${OPENSC_ROOT}/lib" \
			BINARY_PATH="${OPENSC_ROOT}/bin" \
			install || \
			die "make zlib"
	else
		CHOST="${CHOST}" LDCONFIG=true CFLAGS="${CFLAGS} -fPIC -fpic -s" \
			./configure --shared --prefix="${OPENSC_TARGET_ROOT}" || die "configure zlib"
		${MAKE} install DESTDIR="${OPENSC_ROOT}" || die "make zlib"
	fi

	echo "Build libtool"
	cd "${BUILDROOT}/libtool"* || die "cd libtool"
	./configure ${CONFIGOPTS} ${EXTRA_LIBTOOL_CONFIG} || die "Configure libtool"
	${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${OPENSC_ROOT}" || die "make libtool"
	fixup_la

	if [ -n "${BUILD_FOR_WINDOWS}" ]; then
		echo "Build iconv"
		cd "${BUILDROOT}/libiconv"* || die "cd iconv"
		./configure ${CONFIGOPTS} ${EXTRA_ICONV_CONFIG} || die "Configure iconv"
		${MAKE} ${MAKEOPTS} install DESTDIR="${OPENSC_ROOT}" || die "make iconv"
		if [ "${DO_STRIP}" = "1" ]; then
			"${CHOST:+${CHOST}-}strip" \
				"${OPENSC_ROOT}/bin/libcharset"*.dll \
				"${OPENSC_ROOT}/bin/libiconv"*.dll \
				"${OPENSC_ROOT}/bin/iconv"
		fi
		fixup_la
	fi

	echo "Build openssl"
	cd "${BUILDROOT}/openssl"* || die "cd openssl"

	./Configure --prefix="/${OPENSC_TARGET_ROOT}" --cross-compile-prefix=${CHOST:+${CHOST}-} \
		shared $(CHOST="${CHOST}" "${SCRIPTROOT}/gentoo.config-0.9.8") \
		zlib-dynamic ${ZLIB_CFLAGS} \
		no-capieng \
		--openssldir=/etc/ssl \
		${EXTRA_OPENSSL_CONFIG} \
		|| die "Configure openssl"
	[ -n "${BUILD_FOR_WINDOWS}" ] && perl util/mkdef.pl crypto ssl NT update
	${MAKE} depend install INSTALL_PREFIX="${OPENSC_ROOT}" INSTALLTOP="/" MANDIR="/tmp" \
		|| die "make openssl"
	rm -fr "${OPENSC_ROOT}/tmp"

	fixup_la

	cd "${SCRIPTROOT}"
	restore_la
}

build_opensc() {
	fixup_la

	local extra_opensc
	echo "${OPENSC_COMPONENTS}" | grep pcsc > /dev/null && extra_opensc="${extra_opensc} --enable-pcsc"

	if echo "${OPENSC_COMPONENTS}" | grep openct > /dev/null; then
		extra_opensc="${extra_opensc} --enable-openct"

		echo "Build openct"
		cd "${BUILDROOT}/openct"* || die "cd openct"
		./configure ${CONFIGOPTS} ${EXTRA_OPENCT_CONFIG} \
			${extra_opensc} --enable-doc \
			|| die "Configure openct"
		${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${OPENSC_ROOT}" || die "make openct"

		fixup_la
	fi

# Disable until we solve license issue
#	if [ -n "${BUILD_FOR_WINDOWS}" ]; then
#		extra_opensc="${extra_opensc} --enable-cardmod"
#	fi

	echo "Build opensc"
	cd "${BUILDROOT}/opensc"* || die "cd opensc"
	./configure ${CONFIGOPTS} ${EXTRA_OPENSC_CONFIG} \
		CFLAGS="${CFLAGS} --include=cardmod-mingw-compat.h -I${SCRIPTROOT}/include" \
		--enable-openssl --enable-zlib ${extra_opensc} --enable-doc \
		|| die "Configure opensc"
	${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${OPENSC_ROOT}" || die "make opensc"

	fixup_la

	cd "${SCRIPTROOT}"
	restore_la
}

build_engine_pkcs11() {

	fixup_la

	echo "Build libp11"
	cd "${BUILDROOT}/libp11"* || die "cd libp11"
	./configure ${CONFIGOPTS} ${EXTRA_LIBP11_CONFIG} \
		--enable-doc \
		|| die "Configure libp11"
	${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${ENGINE_PKCS11_ROOT}" || die "make libp11"

	fixup_la

	echo "Build engine_pkcs11"
	cd "${BUILDROOT}/engine_pkcs11"* || die "cd engine_pkcs11"
	./configure ${CONFIGOPTS} ${EXTRA_ENGINE_PKCS11_CONFIG} \
		--enable-doc \
		--with-enginesdir="/lib/engines" \
		|| die "Configure engine_pkcs11"
	${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${ENGINE_PKCS11_ROOT}" || die "make engine_pkcs11"

	fixup_la

	cd "${SCRIPTROOT}"
	restore_la
}

build_openvpn() {

	fixup_la

	echo "Build lzo"
	cd "${BUILDROOT}/lzo"* || die "cd lzo"
	./configure ${CONFIGOPTS} ${EXTRA_LZO_CONFIG} \
		|| die "Configure lzo"
	${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${OPENVPN_ROOT}" || die "make lzo"

	fixup_la

	echo "Build pkcs11-helper"
	cd "${BUILDROOT}/pkcs11-helper"* || die "cd pkcs11-helper"
	./configure ${CONFIGOPTS} ${EXTRA_PKCS11_HELPER_CONFIG} \
		--disable-crypto-engine-gnutls \
		--disable-crypto-engine-nss \
		|| die "Configure pkcs11-helper"
	${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${OPENVPN_ROOT}" || die "make pkcs11-helper"

	fixup_la

	echo "Build openvpn"
	cd "${BUILDROOT}/openvpn"* || die "cd openvpn"
	./configure ${CONFIGOPTS} ${EXTRA_OPENVPN_CONFIG} \
		CPPFLAGS="-I${OPENSC_ROOT}/include -I${OPENVPN_ROOT}/include" \
		LDFLAGS="-L${OPENSC_ROOT}/lib -L${OPENVPN_ROOT}/lib" \
		OPENSSL_LIBS="${OPENSSL_FULL_LIBS}" \
		|| die "Configure openvpn"
	${MAKE} ${MAKEOPTS} ${MAKE_AUTOCONF_INSTALL_TARGET} DESTDIR="${OPENVPN_ROOT}" || die "make openvpn"

	fixup_la

	cd "${SCRIPTROOT}"
	restore_la
}

copy_docs() {
	echo "Copying documents"
	mkdir -p "${OPENSC_ROOT}/share/doc/package"
	cp "${SCRIPTROOT}/README" "${SCRIPTROOT}/COPYING"* "${OPENSC_ROOT}/share/doc/package" || die "package docs"
}

copy_sources() {
	echo "Copying sources"
	mkdir -p "${IMAGEROOT}/src/patches"
	cp "${SOURCESROOT}"/* "${IMAGEROOT}/src" || die "sources"
	cp "${PATCHDIR}"/* "${IMAGEROOT}/src/patches" || die "patches"
}

clean_empty_dirs() {
	echo "Cleaning empty directories"
	find "${IMAGEROOT}" -type d | sort -r | xargs rmdir 2> /dev/null
}

# Fixed in libtool-2
fixup_libtool_win_strip() {
	if [ -n "${BUILD_FOR_WINDOWS}" -a "${DO_STRIP}" = "1" ]; then
		find "${IMAGEROOT}" -name '*.dll' | xargs "${CHOST:+${CHOST}-}strip"
	fi
}

pack() {
	echo "Packing images"
	local X="${CHOST:-$(gcc -dumpmachine)}"
	(cd "${IMAGEROOT}" && find src ) | bzip2 > "${IMAGEROOT}/opensc-${X}-${BUILD_VERSION}-srclist.bz2" || die "srclist"
	tar -cjf "${IMAGEROOT}/opensc-${X}-${BUILD_VERSION}-src.tar.bz2" -C "${IMAGEROOT}" src || die "src"
	tar -cjf "${IMAGEROOT}/opensc-${X}-${BUILD_VERSION}-base.tar.bz2" -C "${OPENSC_ROOT}" . || die "base"
	tar -cjf "${IMAGEROOT}/opensc-${X}-${BUILD_VERSION}-engine_pkcs11.tar.bz2" -C "${ENGINE_PKCS11_ROOT}" . || die "engine_pkcs11"
	tar -cjf "${IMAGEROOT}/opensc-${X}-${BUILD_VERSION}-openvpn.tar.bz2" -C "${OPENVPN_ROOT}" . || die "openvpn"
}

nsis() {
	echo "Make windows install"
	sed "s/@BUILD_VERSION@/${BUILD_VERSION}/g" ${SCRIPTROOT}/nsis/opensc-setup.nsi.in > ${IMAGEROOT}/opensc-setup.nsi  
	${MAKENSIS} ${IMAGEROOT}/opensc-setup.nsi  || die 'makensis'
}

SCRIPTROOT="$(get_full_path "$(dirname "$0")")"

#CHOST
#CTARGET
CBUILD="${CBUILD:-${CHOST}}"
IMAGEROOT="${IMAGEROOT:-${SCRIPTROOT}/image}"
BUILDROOT="${BUILDROOT:-${SCRIPTROOT}/tmp}"
SOURCESROOT="${SOURCESROOT:-${SCRIPTROOT}/sources}"
PATCHDIR="${SCRIPTROOT}/patches"

. "${SCRIPTROOT}/build.vars" || die "Cannot source build.vars"

echo "${CHOST:-$(gcc -dumpmachine)}" | grep mingw > /dev/null && BUILD_FOR_WINDOWS=1
which "${WGET}" > /dev/null 2>&1 && WGET_MODE=1

CONFIGOPTS=" \
	--prefix=${OPENSC_TARGET_ROOT} \
	--host=${CHOST} \
	--target=${CTARGET} \
	--build=${CBUILD} \
	--program-prefix='' \
"

OPENSC_ROOT="${IMAGEROOT}/opensc"
ENGINE_PKCS11_ROOT="${IMAGEROOT}/engine_pkcs11"
OPENVPN_ROOT="${IMAGEROOT}/openvpn"

if [ "${DO_STRIP}" = "1" ]; then
	MAKE_AUTOCONF_INSTALL_TARGET="install-strip"
else
	MAKE_AUTOCONF_INSTALL_TARGET="install"
fi

export LTLIB_CFLAGS="-I${OPENSC_ROOT}/include"
export LTLIB_LIBS="-L${OPENSC_ROOT}/lib -lltdl"
export ZLIB_CFLAGS="${LTLIB_CFLAGS}"
export ZLIB_LIBS="-L${OPENSC_ROOT}/lib -lz"
export OPENSSL_CFLAGS="${LTLIB_CFLAGS}"
export OPENSSL_LIBS="-L${OPENSC_ROOT}/lib -lcrypto"
export OPENSSL_FULL_LIBS="-L${OPENSC_ROOT}/lib -lssl -lcrypto"
export OPENCT_CFLAGS="${LTLIB_CFLAGS}"
export OPENCT_LIBS="-L${OPENSC_ROOT}/lib -lopenct"
export LIBP11_CFLAGS="-I${ENGINE_PKCS11_ROOT}/include"
export LIBP11_LIBS="-L${ENGINE_PKCS11_ROOT}/lib -lp11"
export LZO_CFLAGS="-I${OPENVPN_ROOT}/include"
export LZO_LIBS="-L${OPENVPN_ROOT}/lib -llzo2"
export PKCS11_HELPER_CFLAGS="-I${OPENVPN_ROOT}/include"
export PKCS11_HELPER_LIBS="-L${OPENVPN_ROOT}/lib -lpkcs11-helper"

if [ -n "${BUILD_FOR_WINDOWS}" ]; then
	CONFIGOPTS=" \
		${CONFIGOPTS} \
		--sbindir=/bin \
	"
	OPENSC_COMPONENTS="pcsc"
	export PKG_CONFIG="true"
	export MAN2HTML="true"
	export ZLIB_LIBS="-L${OPENSC_ROOT}/lib -lzdll"
	export ICONV_CFLAGS="-I${OPENSC_ROOT}/include"
	export ICONV_LIBS="-L${OPENSC_ROOT}/lib -liconv"
fi

download
create_layout
extract
fixup_win64_libtool
build_dep
build_opensc
build_engine_pkcs11
build_openvpn
copy_docs
copy_sources
clean_empty_dirs
fixup_libtool_win_strip
pack

# disable this until we have nsis working on x86_64
#[ -n "${BUILD_FOR_WINDOWS}" ] && nsis

exit 0
