#!/bin/sh

die() {
	local m="$1"
	echo "FATAL: ${m}" >&2
	exit 1
}

get_full_path() {
	local d="$1"
	( cd "${d}" 2> /dev/null && pwd )
}

CHOST="x86_64-pc-mingw32"
MAKE="${MAKE:-make}"
SCRIPTROOT="$(get_full_path "$(dirname "$0")")"
BUILDROOT="${BUILDROOT:-${SCRIPTROOT}/tmp}"
SOURCESROOT="${SOURCESROOT:-${SCRIPTROOT}/sources}"
BINUTILS_SRC="${BINUTILS_SRC:-${SOURCESROOT}/binutils}"
GCC_SRC="${GCC_SRC:-${SOURCESROOT}/gcc}"
MINGW_W64_SRC="${MINGW_W64_SRC:-${SOURCESROOT}/mingw-w64}"
SYSROOT="${SCRIPTROOT}/sysroot"
TOOLCHAIN_ROOT="${SCRIPTROOT}/toolchain"

BINUTILS_SRC="$(get_full_path "${BINUTILS_SRC}")"
GCC_SRC="$(get_full_path "${GCC_SRC}")"
MINGW_W64_SRC="$(get_full_path "${MINGW_W64_SRC}")"

[ -e "${BINUTILS_SRC}" ] || die "Cannot find binutils sources"
[ -e "${GCC_SRC}" ] || die "Cannot find gcc sources"
[ -e "${MINGW_W64_SRC}" ] || die "Cannot find mingw-w64 sources"

rm -fr "${BUILDROOT}" "${SYSROOT}" "${TOOLCHAIN_ROOT}" || die "clean"

if [ -n "${DO_UPDATE}" ]; then
	if [ -d "${BINUTILS_SRC}/CVS" ]; then
		( cd "${BINUTILS_SRC}"; cvs update ) || die "binutils.update"
	fi
	if [ -d "${GCC_SRC}/.svn" ]; then
		svn update "${GCC_SRC}" || die "gcc.update"
		( cd "${GCC_SRC}"; ./contrib/gcc_update --touch )
	fi
	if [ -d "${MINGW_W64_SRC}/.svn" ]; then
		svn update "${MINGW_W64_SRC}" || die "mingw-w64.update"
	fi
fi

mkdir -p "${BUILDROOT}/binutils"
cd "${BUILDROOT}/binutils"
"${BINUTILS_SRC}/configure" \
	--target="${CHOST}" \
	--prefix="${TOOLCHAIN_ROOT}" \
	--with-sysroot="${SYSROOT}" \
	--without-x \
	--disable-gdbtk \
	|| die "binutils.configure"
${MAKE} ${MAKEOPTS} all-host || die "binutils.make.1"
${MAKE} ${MAKEOPTS} install-host || die "binutils.install.1"

svn export "${MINGW_W64_SRC}/mingw-w64-headers/include" "${TOOLCHAIN_ROOT}/${CHOST}/include" || die "mingw-w64-headers.install"
mkdir -p "${SYSROOT}"
ln -s "${TOOLCHAIN_ROOT}/${CHOST}" "${SYSROOT}/mingw" || die "ln"

mkdir -p "${BUILDROOT}/gcc"
cd "${BUILDROOT}/gcc"
"${GCC_SRC}/configure" \
	--target="${CHOST}" \
	--prefix="${TOOLCHAIN_ROOT}" \
	--with-sysroot="${SYSROOT}" \
	--enable-languages="c,c++" \
	|| die "gcc.configure"
${MAKE} ${MAKEOPTS} all-gcc || die "gcc.make.1"
${MAKE} ${MAKEOPTS} install-gcc || die "gcc.install.1"

export PATH="${TOOLCHAIN_ROOT}/bin:${PATH}"

mkdir -p "${BUILDROOT}/mingw-w64-crt"
cd "${BUILDROOT}/mingw-w64-crt"
"${MINGW_W64_SRC}/mingw-w64-crt/configure" \
	--host="${CHOST}" \
	--prefix="${TOOLCHAIN_ROOT}" \
	--with-sysroot="${SYSROOT}" \
	|| die "mingw-w64-crt.configure"
${MAKE} ${MAKEOPTS} || die "mingw-w64-crt.make"
${MAKE} ${MAKEOPTS} install || die "mingw-w64-crt.install"

cd "${BUILDROOT}/gcc"
${MAKE} ${MAKEOPTS} || die "gcc.make"
${MAKE} ${MAKEOPTS} install || die "gcc.install"
