#define __deref
#define __deref_opt_inout_bcount_part_opt(x,y)
#define __deref_opt_out_bcount(x)
#define __deref_out_bcount(x)
#define __deref_out_bcount_opt(x)
#define __deref_out_ecount(x)
#define __in
#define __in_bcount(x)
#define __in_bcount_opt(x)
#define __in_ecount(x)
#define __in_opt
#define __inout
#define __inout_bcount_full(x)
#define __inout_bcount_opt(x)
#define __out
#define __out_bcount(x)
#define __out_bcount_full(x)
#define __out_bcount_part_opt(x,y)
#define __out_bcount_part_opt(x,y)
#define __out_ecount(x)
#define __out_opt
#define __struct_bcount(x)
#define __success(x)
